name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Stage 1 - Test
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pytest tests/ -v

  # Stage 2 - Build
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2

      - name: Build container
        run: docker build -t vdi-session-broker:${{ github.sha }} .
      
      - name: Test container
        run: |
          docker run -d -p 8000:8000 --name test vdi-session-broker:${{ github.sha }}
          
          for i in {1..15}; do
            if curl -f http://localhost:8000/docs 2>/dev/null; then
              break
            fi
            sleep 2
          done
          
          curl -f -X POST http://localhost:8000/sessions -H "Content-Type: application/json" -d '{"userId": "cicdtest"}'
          docker stop test && docker rm test
      
      - name: Security Scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd):/app aquasec/trivy:latest image \
            --severity HIGH,CRITICAL vdi-session-broker:${{ github.sha }}
        continue-on-error: true  # ONLY FOR INTERVIEW PURPOSES, DO NOT USE IN PRODUCTION
        

  # Stage 3 - Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    steps:
    - run: echo "Ready for deployment."